CREATE DATABASE QLY_BAN_CAFE
GO
USE QLY_BAN_CAFE
GO
CREATE TABLE TABLEFOOD(
 ID INT IDENTITY PRIMARY KEY,
 TEN NVARCHAR(100) not null DEFAULT N'Bàn chưa có tên' ,
 STATUS NVARCHAR(100) not null default N'Trống',
 )
 GO
 CREATE TABLE ACCOUNT(
 
 DISPLAYNAME NVARCHAR(100) NOT NULL DEFAULT N'NHOMHAI',
 USERNAME NVARCHAR(100) PRIMARY KEY,
 PASSWORD NVARCHAR(1000) NOT NULL DEFAULT 0,
 TYPE INT NOT NULL DEFAULT 0,
 )
 GO
 CREATE TABLE FOODCATEGORY(
 ID INT IDENTITY PRIMARY KEY,
 TEN NVARCHAR(100) NOT NULL DEFAULT N'CHƯA ĐẶT TÊN',

 )
 GO
 CREATE TABLE FOOD(
 ID INT IDENTITY PRIMARY KEY,
 TEN NVARCHAR(100)NOT NULL DEFAULT N'CHƯA ĐẶT TÊN',
 IDCATEGORY INT NOT NULL,
 PRICE FLOAT NOT NULL DEFAULT 0,

 foreign key (IDCATEGORY) REFERENCES FOODCATEGORY(ID)

 )
 GO
 CREATE TABLE BILL(
 ID INT IDENTITY PRIMARY KEY,
 DATECHECKIN DATE NOT NULL DEFAULT GETDATE(),
 DATECHECKOUT DATE,
 IDTABLE INT NOT NULL,
 STATUS INT NOT NULL DEFAULT 0, 
 foreign key (IDTABLE) REFERENCES TABLEFOOD(ID)
 )
 GO
 CREATE TABLE BILLINFO(
 ID INT IDENTITY PRIMARY KEY
 ,IDBILL INT NOT NULL,
 IDFOOD INT NOT NULL,
 COUNT INT NOT NULL DEFAULT 0,
  foreign key (IDBILL) REFERENCES BILL(ID),
   foreign key (IDFOOD) REFERENCES FOOD(ID)

 )
 GO


